name: doc
on: [push]
jobs:
  doc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - run: pwd

      - run: git status

      - run: docker -v

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push
        run: |
          docker build \
          --cache-from ghcr.io/${{ github.repository }}/deployer:latest \
          -t ghcr.io/${{ github.repository }}/deployer:latest .
          docker push ghcr.io/${{ github.repository }}/deployer:latest
