name: doc
on: [push]
jobs:
  doc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - run: pwd

      # Авторизация в реестре GitHub
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Сборка и отправка
      - name: Build and Push
        run: |
          docker build -t ghcr.io/${{ github.repository }}/deployer:latest .
          docker push ghcr.io/${{ github.repository }}/deployer:latest
