name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: echo ${{ variables.TEST_VAR }}
      - run: echo ${{ secretes.TEST_SECRET }}
      - run: npm ci
      - run: npm test
