name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout код
        uses: actions/checkout@v4
      - name: Установка зависимостей
        run: npm ci
      - name: Тест проекта
        run: npm test
